package br.senac.finanblu.modelo.enumeracao;

public enum Atrib {
	PAGO, PAGO_POR_DATA, PAGO_POR_CLIENTE, ABERTO, ABERTO_POR_DATA, ABERTO_POR_CLIENTE, A_VENCER, A_VENCER_POR_DATA, A_VENCER_POR_CLIENTE
}
