package br.senac.finanblu.modelo.enumeracao;

public enum AtributoTitulo {
RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, VALOR_VENDA, DATA_VENDA, FORMA_PAGAMENTO, PARCELA, INSTITUICAO_FINANCEIRA, DATA_VENCIMENTO, DATA_PAGAMENTO, SITUACAO
}
